# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rafter_user_service', '0002_auto_20170707_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=200, unique=True)),
                ('input_list', models.FileField(upload_to='')),
                ('output_list', models.FileField(upload_to='')),
                ('parameter_list', models.FileField(upload_to='')),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysisinstance_creator', to='rafter_user_service.Investigator')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmatoryLoop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmatoryloop_analysis', to='rafter_user_service.Analysis')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmatoryloop_creator', to='rafter_user_service.Investigator')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=200, unique=True)),
                ('result_instance', models.FileField(upload_to='')),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimentinstance_creator', to='rafter_user_service.Investigator')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimentinstance_experiment', to='rafter_user_service.Experiment')),
                ('experiment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimentinstance_experiment_status', to='rafter_user_service.ExperimentStatus')),
            ],
        ),
        migrations.CreateModel(
            name='ExploratoryLoop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exploratoryloop_analysis', to='rafter_user_service.Analysis')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exploratoryloop_creator', to='rafter_user_service.Investigator')),
            ],
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_creator', to='rafter_user_service.Investigator')),
                ('investigation_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_investigation_status', to='rafter_user_service.InvestigationStatus')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_last_modifier', to='rafter_user_service.Investigator')),
            ],
        ),
        migrations.CreateModel(
            name='ModelInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=200, unique=True)),
                ('input_list', models.FileField(upload_to='')),
                ('output_list', models.FileField(upload_to='')),
                ('parameter_list', models.FileField(upload_to='')),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelinstance_creator', to='rafter_user_service.Investigator')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelinstance_investigation', to='rafter_user_service.Investigation')),
                ('model_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelinstance_model_status', to='rafter_user_service.ModelStatus')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelinstance_last_modifier', to='rafter_user_service.Investigator')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_creator', to='rafter_user_service.Investigator')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_last_modifier', to='rafter_user_service.Investigator')),
                ('project_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_project_state', to='rafter_user_service.ProjectState')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_team', to='rafter_user_service.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TheoryInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theoryinstance_creator', to='rafter_user_service.Investigator')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theoryinstance_investigation', to='rafter_user_service.Investigation')),
                ('model', models.ManyToManyField(related_name='theoryinstance_model', to='rafter_user_service.Model')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theoryinstance_last_modifier', to='rafter_user_service.Investigator')),
            ],
        ),
        migrations.AddField(
            model_name='investigation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_project', to='rafter_user_service.Project'),
        ),
        migrations.AddField(
            model_name='exploratoryloop',
            name='investigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exploratoryloop_investigation', to='rafter_user_service.Investigation'),
        ),
        migrations.AddField(
            model_name='exploratoryloop',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exploratoryloop_last_modifier', to='rafter_user_service.Investigator'),
        ),
        migrations.AddField(
            model_name='experimentinstance',
            name='investigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimentinstance_investigation', to='rafter_user_service.Investigation'),
        ),
        migrations.AddField(
            model_name='experimentinstance',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimentinstance_last_modifier', to='rafter_user_service.Investigator'),
        ),
        migrations.AddField(
            model_name='experimentinstance',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimentinstance_treatment', to='rafter_user_service.Treatment'),
        ),
        migrations.AddField(
            model_name='confirmatoryloop',
            name='investigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmatoryloop_investigation', to='rafter_user_service.Investigation'),
        ),
        migrations.AddField(
            model_name='confirmatoryloop',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmatoryloop_last_modifier', to='rafter_user_service.Investigator'),
        ),
        migrations.AddField(
            model_name='analysisinstance',
            name='investigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysisinstance_investigation', to='rafter_user_service.Investigation'),
        ),
        migrations.AddField(
            model_name='analysisinstance',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysisinstance_last_modifier', to='rafter_user_service.Investigator'),
        ),
    ]
