# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rafter_user_service', '0003_profile__token'),
        ('rafter_user_service', '0004_observation'),
    ]

    operations = [
    ]
