# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rafter_user_service', '0006_auto_20170905_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigator',
            name='user_name',
        ),
    ]
