# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rafter_user_service', '0007_remove_investigator_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='observation_project', to='rafter_user_service.Project'),
            preserve_default=False,
        ),
    ]
