# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rafter_user_service', '0009_auto_20170906_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalobservation',
            old_name='date_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='historicalobservation',
            old_name='last_modified',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='date_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='last_modified',
            new_name='modified',
        ),
    ]
