# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 23:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rafter_user_service', '0014_team_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_modified_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
