# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 21:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rafter_user_service', '0016_auto_20170915_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTheory',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('last_modified', models.DateTimeField(blank=True, editable=False)),
                ('text', models.CharField(max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical theory',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.RenameField(
            model_name='theory',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='theory',
            name='date_last_modified',
        ),
        migrations.RemoveField(
            model_name='theory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='theory',
            name='name',
        ),
        migrations.AddField(
            model_name='investigation',
            name='theories',
            field=models.ManyToManyField(related_name='investigation_theory', to='rafter_user_service.Theory'),
        ),
        migrations.AddField(
            model_name='theory',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='theory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='theory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='theory',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
