# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafter_user_service', '0020_auto_20170922_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='models',
            field=models.ManyToManyField(related_name='investigation_model', to='rafter_user_service.Model'),
        ),
    ]
