# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafter_user_service', '0022_auto_20170922_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='mechanisms',
            field=models.ManyToManyField(blank=True, related_name='investigation_mechanism', to='rafter_user_service.Mechanism'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='models',
            field=models.ManyToManyField(blank=True, related_name='investigation_model', to='rafter_user_service.Model'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='theories',
            field=models.ManyToManyField(blank=True, related_name='investigation_theory', to='rafter_user_service.Theory'),
        ),
    ]
