# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafter_user_service', '0024_auto_20170922_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='hypotheses',
            field=models.ManyToManyField(blank=True, related_name='investigation_hypothesis', to='rafter_user_service.Hypothesis'),
        ),
    ]
