# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 15:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rafter_user_service', '0026_auto_20170922_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAnalysis',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('last_modified', models.DateTimeField(blank=True, editable=False)),
                ('text', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('investigation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rafter_user_service.Investigation')),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical analysis',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ['date_created']},
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='date_last_modified',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='description',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='input',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='name',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='output',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='parameter',
        ),
        migrations.AddField(
            model_name='analysis',
            name='investigation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rafter_user_service.Investigation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysis',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
