# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rafter_user_service', '0027_auto_20170922_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rafter_user_service.Project'),
        ),
    ]
