# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafter_user_service', '0028_auto_20170922_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='name',
            field=models.CharField(default='Name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='Name', max_length=200),
            preserve_default=False,
        ),
    ]
