"""
Django settings for django_montage project.

Generated by 'django-admin startproject' using Django 1.11.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/

This file contains defaults for many settings, but all can be overwritten in
prod_settings.py or dev_settings.py.
"""

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

if DEBUG:
    try:
        from .dev_settings import *
    except ImportError:
        pass
else:
    try:
        from .prod_settings import *
    except ImportError:
        pass
