# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('montage_jwt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='JWT',
        ),
    ]
